### ISSUE TITLE
Collection of Ideas

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#12]
bundle them together

http://nextbigfuture.com/?m=1
## 散装的
- [x] [关于太空生育问题](https://github.com/InterImm/InterImmBook/issues/1)
- [ ] [Population Curve](https://github.com/InterImm/InterImmBook/issues/2)
- [x] [ion propulsion](https://github.com/InterImm/InterImmBook/issues/3)
- [x] [新职业新专业](https://github.com/InterImm/InterImmBook/issues/4)
- [ ] [How to locate a ship in deep space](https://github.com/InterImm/InterImmBook/issues/5)
- [ ] [Dynamics of atmosphere on a locked planet](https://github.com/InterImm/InterImmBook/issues/6)
- [x] [cooperation with the Venus project on other planets](https://github.com/InterImm/InterImmBook/issues/10)
- [x] [Mars' Calendar](https://github.com/InterImm/InterImmBook/issues/14)
- [ ] [Mars' Weather](https://www.youtube.com/watch?v=GfwiqBVXH5k&feature=em-subs_digest)
- [ ] [为了科研：引力波探测器阵列，超新星探测器，etc](https://github.com/InterImm/InterImmBook/issues/21)
- [ ] 近地小行星开采。[How to find metal-rich asteroids on arXiv.org](http://arxiv.org/abs/1403.6346)
## 大型的
- [x] [未来历史时间线](https://github.com/InterImm/InterImmBook/issues/17)
